version: "3.3"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: $BACKEND_PORT
    container_name: AIbackend
    volumes:
      - ./src/backend:/app
    env_file:
      - ./src/backend/.env
      - ./.env
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    networks:
      - web

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_PORT: $FRONTEND_PORT
        REACT_APP_BACKEND_HOST: $HOST
        REACT_APP_BACKEND_PORT: $BACKEND_PORT
    container_name: AIfrontend
    volumes:
      - ./src/frontend:/app
    env_file:
      - ./src/frontend/.env
      - ./.env
    ports:
      - "$FRONTEND_PORT:80"
    networks:
      - web

networks:
  web:
    driver: bridge