version: "3.3"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    env_file:
      - ./src/backend/.env
      - ./.env
    ports:
      - "$BACKEND_PORT:8000"
    volumes:
      - ./backend:/app
    networks:
      - web

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        HOST: $FRONTEND_HOST
        PORT: $FRONTEND_PORT
    env_file:
      - ./src/frontend/.env
      - ./.env
    ports:
      - "$FRONTEND_PORT:80"
    networks:
      - web

networks:
  web:
    driver: bridge